name: Sync Fork with Upstream

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0 点自动运行（北京时间 8 点）
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: CCSH/IPTV
          upstream_sync_branch: main
